### ISSUE TITLE
高级成员进入广场权限问题

### ISSUE THREAD

**Issue by aDeterMinism** [acsoto/GuildManager#3]
## 现象

> 玩家``` MCNSS``` 加入公会 ```magic``` 并被设为高级成员后，反复登录（使用了 ```login``` 命令）但，并没有获得权限进入广场。

> 公会上线播报（包括玩家和会长）正常

 @acsoto 

## 猜测
可能是监听 ```LoginEvent``` 的函数出了什么问题

**Comment by aDeterMinism** [comment]
## 什么问题
因为会长通知上线是正常的，可能问题发生在通知上线之后
## 建议
将通知上线后部分去除，
1. 判定玩家权限部分另起函数，还原为原先版本
2. 将给权限、删权限合并到增加高级成员操作函数和移除操作、退出操作函数中

**Comment by acsoto** [comment]
应该是存完数据库内存没刷新的问题，我把逻辑改到增删高级成员那里吧

**Comment by acsoto** [comment]
原因是指令里面的玩家变量类型搞错了😓

**Comment by aDeterMinism** [comment]
@acsoto 
## 按我理解，感觉不对劲
in [GuildCommand.java](https://github.com/acsoto/GuildManager/blob/master/src/main/java/com/mcatk/guildmanager/command/GuildCommand.java) line 173 ``` 需要检查、去除公会广场权限 ```
in [GuildCommandS.java](https://github.com/acsoto/GuildManager/blob/master/src/main/java/com/mcatk/guildmanager/command/GuildCommandS.java) line 146 ``` 需要检查、去除公会广场权限 ```
## 建议
若确实有问题，应该可以直接构造 ```GuildCommandS``` 型新变量（试图证明自己有开发经历）

**Comment by acsoto** [comment]
你说的对，忘记了这两处，已经加上了[6b4ff8e](https://github.com/acsoto/GuildManager/commit/6b4ff8e5aa5c7cf8f24955ced1a7a9e5227ef2e6)，之前就是因为要检测的地方太多所以直接写到进入事件里面了，也可以写一个定时任务。

**Comment by aDeterMinism** [comment]
## 一个小 bug
in [GuildCommand.java](https://github.com/acsoto/GuildManager/blob/master/src/main/java/com/mcatk/guildmanager/command/GuildCommand.java) line 175 ```是不是把 remove 写成了 true ``` 😂 

同时 line 176 似乎改为 ```guild.getGuildName()``` 更合理

**Comment by acsoto** [comment]
是的，都是copilot的锅😅
